# 4.8 GROUPING DATA & AGGREGATING VARIABLES
** **

**SCRIPT CONTENTS:**

1. Importing Libraries & Files
2. Grouping Data
3. Grouping Data with pandas
4. Aggregating Data with agg()
5. Aggregating Data with transform()
6. Deriving Columns wih loc()
7. Exporting Updated DataFrame: **orders_products_merged_update2.pkl**

****
#### 1. IMPORTING LIBRARIES & FILES

In [1]:
# Import libraries
import pandas as pd
import numpy as np
import os

In [2]:
# Document File Location
path = r'C:\Users\G\12-2022 Instacart Basket Analysis'

In [3]:
# Import Merge Pickle Format File
ords_prods_merge = pd.read_pickle(os.path.join(path, '02 Data', 'Prepared Data', 'orders_products_merged_update.pkl'))

** **
#### 2. GROUPING DATA

In [4]:
# Create a Subset

df = ords_prods_merge[:1000000]

In [5]:
# Check DataFrame Shape

ords_prods_merge.shape

(32404859, 19)

In [6]:
# Check DataFrame Column

ords_prods_merge.head()

,order_id,customer_id,order_number,order_day_of_week,order_hour_of_day,days_since_prior_order,new_customer,product_id,add_to_cart_order,reordered,product_name,aisle_id,department_id,prices,_merge,price_range,busiest_day,busiest days,busiest_period_of_day
0,2539329,1,1,2,8,NaN,True,196,1,0,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Regularly busy,Most orders
1,2398795,1,2,3,7,15.0,False,196,1,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Slowest days,Average orders
2,473747,1,3,3,12,21.0,False,196,1,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Slowest days,Most orders
3,2254736,1,4,4,7,29.0,False,196,1,1,Soda,77,7,9.0,both,Mid-range product,Least busy,Slowest days,Average orders
4,431534,1,5,4,15,28.0,False,196,1,1,Soda,77,7,9.0,both,Mid-range product,Least busy,Slowest days,Most orders

#### 3. GROUPING DATA WITH PANDAS

In [7]:
ords_prods_merge.groupby('product_name')

What has pandas done here? Well, the **groupby()** function has apparently created a pandas object (indicated by the term “object” in the output message above). But now what? Nothing seems to have actually happened.

This is because the output of the **groupby()** function isn’t visible. Though it executed successfully (as evidenced by the output message you received), it’s not something that you, as the coder, can actually see. It needs you to do something else, for instance, _aggregate the data or apply a function (the second step of the workflow)_, before you’ll be able to see the results. In other words, by itself, the **groupby()** function is a little worthless in terms of output.

** **

**Q2) In this Exercise, you learned how to find the aggregated mean of the “order_number” column grouped by “department_id” for a subset of your dataframe. Now, repeat this process for the** _entire_ **dataframe.**

In [8]:
# OPTION 1: Average number of orders per department-id

ords_prods_merge.groupby('department_id').agg({'order_number': ['mean']})

              order_number
                      mean
department_id
1                15.457838
2                17.277920
3                17.170395
4                17.811403
5                15.215751
6                16.439806
7                17.225802
8                15.340650
9                15.895474
10               20.197148
11               16.170638
12               15.887671
13               16.583536
14               16.773669
15               16.165037
16               17.665606
17               15.694469
18               19.310397
19               17.177343
20               16.473447
21               22.902379

**OBSERVATION:**  The department with an ID no. of 4 (produce) has a mean of around 18. Conversely, the department with an ID no. of 17 (household), only has a mean of around 16. The insight you can glean from this is that produce sells considerably more on average than household goods.

In [9]:
# OPTION 2 Finding mean

ords_prods_merge.groupby('department_id')['order_number'].mean()

department_id
1     15.457838
2     17.277920
3     17.170395
4     17.811403
5     15.215751
6     16.439806
7     17.225802
8     15.340650
9     15.895474
10    20.197148
11    16.170638
12    15.887671
13    16.583536
14    16.773669
15    16.165037
16    17.665606
17    15.694469
18    19.310397
19    17.177343
20    16.473447
21    22.902379
Name: order_number, dtype: float64

In [10]:
# OPTION 3 Finding mean

ords_prods_merge.groupby('department_id').order_number.mean()

department_id
1     15.457838
2     17.277920
3     17.170395
4     17.811403
5     15.215751
6     16.439806
7     17.225802
8     15.340650
9     15.895474
10    20.197148
11    16.170638
12    15.887671
13    16.583536
14    16.773669
15    16.165037
16    17.665606
17    15.694469
18    19.310397
19    17.177343
20    16.473447
21    22.902379
Name: order_number, dtype: float64

In [11]:
# Statistical calculation of orders per department_id

ords_prods_merge.groupby('department_id').agg({'order_number': ['mean']})

              order_number
                      mean
department_id
1                15.457838
2                17.277920
3                17.170395
4                17.811403
5                15.215751
6                16.439806
7                17.225802
8                15.340650
9                15.895474
10               20.197148
11               16.170638
12               15.887671
13               16.583536
14               16.773669
15               16.165037
16               17.665606
17               15.694469
18               19.310397
19               17.177343
20               16.473447
21               22.902379

** **
#### 4. AGGREGATING DATA WITH AGG()

**Q3) Analyze the result. How do the results for the entire dataframe differ from those of the subset? Include your comments in a markdown cell below the executed code.**

In [12]:
# Statistical calculation of orders per department_id comparing to a subset

df.groupby('department_id').agg({'order_number': ['mean']})

              order_number
                      mean
department_id
4                18.825780
7                17.472355
13               17.993423
14               19.246334
16               19.463012
17               11.294069
19               19.305237
20               17.599636

**OBSERVATION:** The aggregation on subset is basing of its calculation within the 1000000 rows selected as opposed to averaging the entire dataframe value.

****
**Q4) Follow the instructions in the Exercise for creating a loyalty flag for existing customers using the** _transform()_ **and** _loc()_ **functions.**

#### 5. Aggregating Data with transform()

To create flag, you’ll need some criteria. You can use the following:

 - If the maximum orders the user has made is over 40, then the customer will be labeled a “Loyal customer.”
 - If the maximum orders the user has made is over 10 but less than or equal to 40, then the customer will be labeled a “Regular customer.”
 - If the maximum orders the user has made is less than or equal to 10, then the customer will be labeled a “New customer.”

In [13]:
# LOYALTY FLAG: Create max_order column with aggregated oder_number by customer_id

ords_prods_merge['max_order'] = ords_prods_merge.groupby(['customer_id'])['order_number'].transform(np.max)

Three-step process in a single line of code:

   1. Split the data into groups based on the “customer_id” column.
   2. Apply the **transform()** function on the “order_number” column to generate the maximum orders for each user.
   3. Create a new column, “max_order,” into which you’ll place the results of your aggregation.

In [14]:
# Check Output

pd.options.display.max_rows = None

ords_prods_merge.head(100)

,order_id,customer_id,order_number,order_day_of_week,order_hour_of_day,days_since_prior_order,new_customer,product_id,add_to_cart_order,reordered,product_name,aisle_id,department_id,prices,_merge,price_range,busiest_day,busiest days,busiest_period_of_day,max_order
0,2539329,1,1,2,8,NaN,True,196,1,0,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Regularly busy,Most orders,10
1,2398795,1,2,3,7,15.0,False,196,1,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Slowest days,Average orders,10
2,473747,1,3,3,12,21.0,False,196,1,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Slowest days,Most orders,10
3,2254736,1,4,4,7,29.0,False,196,1,1,Soda,77,7,9.0,both,Mid-range product,Least busy,Slowest days,Average orders,10
4,431534,1,5,4,15,28.0,False,196,1,1,Soda,77,7,9.0,both,Mid-range product,Least busy,Slowest days,Most orders,10
5,3367565,1,6,2,7,19.0,False,196,1,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Regularly busy,Average orders,10
6,550135,1,7,1,9,20.0,False,196,1,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Busiest days,Most orders,10
7,3108588,1,8,1,14,14.0,False,196,2,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Busiest days,Most orders,10
8,2295261,1,9,1,16,0.0,False,196,4,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Busiest days,Most orders,10
9,2550362,1,10,4,8,30.0,False,196,1,1,Soda,77,7,9.0,both,Mid-range product,Least busy,Slowest days,Most orders,10
10,2968173,15,15,1,9,7.0,False,196,2,0,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Busiest days,Most orders,22
11,1870022,15,17,2,16,8.0,False,196,6,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Regularly busy,Most orders,22
12,1911383,15,18,2,11,7.0,False,196,1,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Regularly busy,Most orders,22
13,2715276,15,21,1,9,7.0,False,196,1,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Busiest days,Most orders,22
14,487368,15,22,1,10,14.0,False,196,1,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Busiest days,Most orders,22
15,2293453,19,2,5,14,6.0,False,196,3,0,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Regularly busy,Most orders,9
16,1973799,19,5,6,12,8.0,False,196,15,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Regularly busy,Most orders,9
17,532817,19,7,4,17,6.0,False,196,1,1,Soda,77,7,9.0,both,Mid-range product,Least busy,Slowest days,Most orders,9
18,1573906,21,10,3,10,6.0,False,196,2,0,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Slowest days,Most orders,33
19,1593000,31,10,3,8,7.0,False,196,17,0,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Slowest days,Most orders,20
20,2231262,31,17,3,11,8.0,False,196,14,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Slowest days,Most orders,20
21,2580647,43,6,4,16,4.0,False,196,9,0,Soda,77,7,9.0,both,Mid-range product,Least busy,Slowest days,Most orders,11
22,2187180,43,9,4,12,3.0,False,196,1,1,Soda,77,7,9.0,both,Mid-range product,Least busy,Slowest days,Most orders,11
23,2497897,52,1,1,9,NaN,True,196,4,0,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Busiest days,Most orders,27
24,1318871,52,2,1,10,7.0,False,196,5,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Busiest days,Most orders,27
25,1261384,52,3,1,10,7.0,False,196,3,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Busiest days,Most orders,27
26,580568,52,5,2,10,8.0,False,196,6,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Regularly busy,Most orders,27
27,2428073,52,7,2,7,8.0,False,196,5,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Regularly busy,Average orders,27
28,342306,52,9,1,11,7.0,False,196,5,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Busiest days,Most orders,27
29,1520353,52,10,2,10,8.0,False,196,4,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Regularly busy,Most orders,27
30,2542086,52,11,2,9,7.0,False,196,3,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Regularly busy,Most orders,27
31,944694,52,12,1,16,6.0,False,196,7,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Busiest days,Most orders,27
32,1268191,52,15,2,11,8.0,False,196,3,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Regularly busy,Most orders,27
33,1122089,52,17,2,10,6.0,False,196,4,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Regularly busy,Most orders,27
34,1498922,52,18,2,10,14.0,False,196,6,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Regularly busy,Most orders,27
35,180919,52,19,3,8,8.0,False,196,4,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Slowest days,Most orders,27
36,2695875,52,21,5,10,30.0,False,196,1,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Regularly busy,Most orders,27
37,3205960,67,1,3,11,NaN,True,196,1,0,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Slowest days,Most orders,24
38,970922,67,2,1,15,5.0,False,196,2,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Busiest days,Most orders,24
39,596585,67,3,1,13,7.0,False,196,2,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Busiest days,Most orders,24
40,2037087,67,4,2,9,8.0,False,196,1,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Regularly busy,Most orders,24
41,2474111,67,5,3,14,8.0,False,196,2,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Slowest days,Most orders,24
42,1568481,67,6,3,12,7.0,False,196,2,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Slowest days,Most orders,24
43,2048527,67,8,2,11,7.0,False,196,1,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Regularly busy,Most orders,24
44,2389031,67,9,2,14,7.0,False,196,1,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Regularly busy,Most orders,24
45,2378562,67,10,1,10,6.0,False,196,1,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Busiest days,Most orders,24
46,1515698,67,11,1,11,7.0,False,196,1,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Busiest days,Most orders,24
47,1928050,67,12,2,12,8.0,False,196,1,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Regularly busy,Most orders,24
48,1949274,67,13,1,10,6.0,False,196,1,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Busiest days,Most orders,24
49,551869,67,14,1,9,7.0,False,196,1,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Busiest days,Most orders,24
50,768572,67,16,4,10,9.0,False,196,1,1,Soda,77,7,9.0,both,Mid-range product,Least busy,Slowest days,Most orders,24
51,150528,67,18,5,16,4.0,False,196,1,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Regularly busy,Most orders,24
52,29758,67,19,0,14,9.0,False,196,2,1,Soda,77,7,9.0,both,Mid-range product,Busiest day,Busiest days,Most orders,24
53,1558976,67,21,1,9,5.0,False,196,2,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Busiest days,Most orders,24
54,863974,67,22,1,11,14.0,False,196,3,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Busiest days,Most orders,24
55,2308399,67,23,1,14,14.0,False,196,1,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Busiest days,Most orders,24
56,2759128,81,3,1,9,14.0,False,196,2,0,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Busiest days,Most orders,7
57,1812985,81,5,2,20,30.0,False,196,1,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Regularly busy,Average orders,7
58,1889835,82,1,3,15,NaN,True,196,6,0,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Slowest days,Most orders,19
59,499460,82,3,5,10,5.0,False,196,2,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Regularly busy,Most orders,19
60,2728456,82,4,0,11,16.0,False,196,1,1,Soda,77,7,9.0,both,Mid-range product,Busiest day,Busiest days,Most orders,19
61,2653743,82,6,4,9,13.0,False,196,5,1,Soda,77,7,9.0,both,Mid-range product,Least busy,Slowest days,Most orders,19
62,1358880,82,9,1,10,30.0,False,196,1,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Busiest days,Most orders,19
63,343588,82,10,2,11,1.0,False,196,1,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Regularly busy,Most orders,19
64,3034663,82,15,2,11,12.0,False,196,1,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Regularly busy,Most orders,19
65,147262,82,18,1,13,7.0,False,196,1,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Busiest days,Most orders,19
66,3144004,82,19,2,15,8.0,False,196,1,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Regularly busy,Most orders,19
67,2126069,98,3,0,9,25.0,False,196,7,0,Soda,77,7,9.0,both,Mid-range product,Busiest day,Busiest days,Most orders,14
68,2210120,98,7,5,14,5.0,False,196,1,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Regularly busy,Most orders,14
69,681011,98,9,3,9,30.0,False,196,1,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Slowest days,Most orders,14
70,2846344,98,11,4,13,15.0,False,196,2,1,Soda,77,7,9.0,both,Mid-range product,Least busy,Slowest days,Most orders,14
71,747431,98,12,6,13,30.0,False,196,4,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Regularly busy,Most orders,14
72,2383054,98,13,4,11,30.0,False,196,1,1,Soda,77,7,9.0,both,Mid-range product,Least busy,Slowest days,Most orders,14
73,1993729,98,14,5,8,8.0,False,196,2,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Regularly busy,Most orders,14
74,1403849,109,3,3,17,9.0,False,196,5,0,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Slowest days,Most orders,6
75,520620,120,1,3,11,NaN,True,196,2,0,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Slowest days,Most orders,3
76,3273029,120,3,2,8,19.0,False,196,2,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Regularly busy,Most orders,3
77,1861943,185,2,1,12,25.0,False,196,10,0,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Busiest days,Most orders,6
78,2040988,195,1,1,14,NaN,True,196,2,0,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Busiest days,Most orders,58
79,1680569,195,8,1,9,4.0,False,196,2,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Busiest days,Most orders,58
80,276171,195,19,5,11,3.0,False,196,2,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Regularly busy,Most orders,58
81,2744976,195,22,5,10,7.0,False,196,2,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Regularly busy,Most orders,58
82,2781919,195,25,1,14,4.0,False,196,1,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Busiest days,Most orders,58
83,1738718,195,31,2,8,4.0,False,196,2,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Regularly busy,Most orders,58
84,3058369,195,34,3,10,6.0,False,196,2,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Slowest days,Most orders,58
85,1485596,195,37,2,15,0.0,False,196,2,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Regularly busy,Most orders,58
86,417035,195,40,3,16,2.0,False,196,2,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Slowest days,Most orders,58
87,1615297,195,47,5,10,2.0,False,196,2,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Regularly busy,Most orders,58
88,1765587,195,52,3,12,2.0,False,196,3,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Slowest days,Most orders,58
89,745908,195,57,4,11,3.0,False,196,3,1,Soda,77,7,9.0,both,Mid-range product,Least busy,Slowest days,Most orders,58
90,2505656,222,17,2,12,1.0,False,196,2,0,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Regularly busy,Most orders,70
91,3268370,222,38,5,15,1.0,False,196,6,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Regularly busy,Most orders,70
92,2016711,290,9,5,19,6.0,False,196,8,0,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Regularly busy,Most orders,51
93,2706088,290,28,6,10,7.0,False,196,16,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Regularly busy,Most orders,51
94,1952286,331,6,5,16,30.0,False,196,8,0,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Regularly busy,Most orders,8
95,3226575,360,1,5,12,NaN,True,196,1,0,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Regularly busy,Most orders,3
96,1469869,377,3,5,17,3.0,False,196,9,0,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Regularly busy,Most orders,3
97,1927023,387,2,4,10,22.0,False,196,3,0,Soda,77,7,9.0,both,Mid-range product,Least busy,Slowest days,Most orders,8
98,858092,420,4,1,19,30.0,False,196,2,0,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Busiest days,Most orders,22
99,119314,420,5,3,19,16.0,False,196,2,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Slowest days,Most orders,22

#### 6.Deriving Columns with loc()

With your new column ready to go, all that’s left is to create a flag that assigns a “loyalty” label to a user ID based on its corresponding max order value.

In [15]:
# FLAG: Loyal customer (highest order_number value)

ords_prods_merge.loc[ords_prods_merge['max_order'] > 40, 'loyalty_flag'] = 'Loyal customer'

In [16]:
# FLAG: Regular customer (median order_number value)

ords_prods_merge.loc[(ords_prods_merge['max_order'] <= 40) & (ords_prods_merge['max_order'] > 10), 'loyalty_flag'] = 'Regular customer'

In [17]:
# FLAG: New customer (lowest order_number value)

ords_prods_merge.loc[ords_prods_merge['max_order'] <= 10, 'loyalty_flag'] = 'New customer'

In [18]:
# Check Output of loyalty flag

ords_prods_merge['loyalty_flag'].value_counts(dropna = False)

Regular customer    15876776
Loyal customer      10284093
New customer         6243990
Name: loyalty_flag, dtype: int64

In [19]:
# Check columns of loyalty flag

ords_prods_merge[['customer_id', 'loyalty_flag', 'order_number']].head(100)

    customer_id      loyalty_flag  order_number
0             1      New customer             1
1             1      New customer             2
2             1      New customer             3
3             1      New customer             4
4             1      New customer             5
5             1      New customer             6
6             1      New customer             7
7             1      New customer             8
8             1      New customer             9
9             1      New customer            10
10           15  Regular customer            15
11           15  Regular customer            17
12           15  Regular customer            18
13           15  Regular customer            21
14           15  Regular customer            22
15           19      New customer             2
16           19      New customer             5
17           19      New customer             7
18           21  Regular customer            10
19           31  Regular customer            10
20           31  Regular customer            17
21           43  Regular customer             6
22           43  Regular customer             9
23           52  Regular customer             1
24           52  Regular customer             2
25           52  Regular customer             3
26           52  Regular customer             5
27           52  Regular customer             7
28           52  Regular customer             9
29           52  Regular customer            10
30           52  Regular customer            11
31           52  Regular customer            12
32           52  Regular customer            15
33           52  Regular customer            17
34           52  Regular customer            18
35           52  Regular customer            19
36           52  Regular customer            21
37           67  Regular customer             1
38           67  Regular customer             2
39           67  Regular customer             3
40           67  Regular customer             4
41           67  Regular customer             5
42           67  Regular customer             6
43           67  Regular customer             8
44           67  Regular customer             9
45           67  Regular customer            10
46           67  Regular customer            11
47           67  Regular customer            12
48           67  Regular customer            13
49           67  Regular customer            14
50           67  Regular customer            16
51           67  Regular customer            18
52           67  Regular customer            19
53           67  Regular customer            21
54           67  Regular customer            22
55           67  Regular customer            23
56           81      New customer             3
57           81      New customer             5
58           82  Regular customer             1
59           82  Regular customer             3
60           82  Regular customer             4
61           82  Regular customer             6
62           82  Regular customer             9
63           82  Regular customer            10
64           82  Regular customer            15
65           82  Regular customer            18
66           82  Regular customer            19
67           98  Regular customer             3
68           98  Regular customer             7
69           98  Regular customer             9
70           98  Regular customer            11
71           98  Regular customer            12
72           98  Regular customer            13
73           98  Regular customer            14
74          109      New customer             3
75          120      New customer             1
76          120      New customer             3
77          185      New customer             2
78          195    Loyal customer             1
79          195    Loyal customer             8
80          195    Loyal customer            19
81          195    Loyal customer            22
82          195    Loyal customer            25
83          195    Loyal customer            31
84          195    Loyal customer            34
85          195    Loyal customer            37
86          195    Loyal customer            40
87          195    Loyal customer            47
88          195    Loyal customer            52
89          195    Loyal customer            57
90          222    Loyal customer            17
91          222    Loyal customer            38
92          290    Loyal customer             9
93          290    Loyal customer            28
94          331      New customer             6
95          360      New customer             1
96          377      New customer             3
97          387      New customer             2
98          420  Regular customer             4
99          420  Regular customer             5

** **
**Q5) The marketing team at Instacart wants to know whether there’s a difference between the spending habits of the three types of customers you identified.** 

_Use the loyalty flag you created and check the basic statistics of the product prices for each loyalty category (Loyal Customer, Regular Customer, and New Customer)._**What you’re trying to determine is whether the prices of products purchased by loyal customers differ from those purchased by regular or new customers.**

In [20]:
ords_prods_merge.groupby('loyalty_flag').agg({'prices': ['mean', 'min', 'max', 'sum']})

                     prices
                       mean  min      max          sum
loyalty_flag
Loyal customer    10.386336  1.0  99999.0  106814042.2
New customer      13.294670  1.0  99999.0   83011787.2
Regular customer  12.495717  1.0  99999.0  198391693.2

**OBESERVATION:** The average price the loyal customer that are willing to pay is lower than the regular customers.

** **
**Q6) The team now wants to target different types of spenders in their marketing campaigns. This can be achieved by looking at the prices of the items people are buying. Create a spending flag for each user based on the average price across all their orders using the following criteria:**

 - If the mean of the prices of products purchased by a user is lower than 10, then flag them as a “Low spender.”
 - If the mean of the prices of products purchased by a user is higher than or equal to 10, then flag them as a “High spender.”

In [21]:
# SPENDING FLAG: Create average_price column with aggregated mean price by customer_id

ords_prods_merge['average_price'] = ords_prods_merge.groupby(['customer_id'])['prices'].transform(np.mean)

In [22]:
# Check Output

ords_prods_merge.head(50)

,order_id,customer_id,order_number,order_day_of_week,order_hour_of_day,days_since_prior_order,new_customer,product_id,add_to_cart_order,reordered,...,department_id,prices,_merge,price_range,busiest_day,busiest days,busiest_period_of_day,max_order,loyalty_flag,average_price
0,2539329,1,1,2,8,NaN,True,196,1,0,...,7,9.0,both,Mid-range product,Regularly busy,Regularly busy,Most orders,10,New customer,6.367797
1,2398795,1,2,3,7,15.0,False,196,1,1,...,7,9.0,both,Mid-range product,Regularly busy,Slowest days,Average orders,10,New customer,6.367797
2,473747,1,3,3,12,21.0,False,196,1,1,...,7,9.0,both,Mid-range product,Regularly busy,Slowest days,Most orders,10,New customer,6.367797
3,2254736,1,4,4,7,29.0,False,196,1,1,...,7,9.0,both,Mid-range product,Least busy,Slowest days,Average orders,10,New customer,6.367797
4,431534,1,5,4,15,28.0,False,196,1,1,...,7,9.0,both,Mid-range product,Least busy,Slowest days,Most orders,10,New customer,6.367797
5,3367565,1,6,2,7,19.0,False,196,1,1,...,7,9.0,both,Mid-range product,Regularly busy,Regularly busy,Average orders,10,New customer,6.367797
6,550135,1,7,1,9,20.0,False,196,1,1,...,7,9.0,both,Mid-range product,Regularly busy,Busiest days,Most orders,10,New customer,6.367797
7,3108588,1,8,1,14,14.0,False,196,2,1,...,7,9.0,both,Mid-range product,Regularly busy,Busiest days,Most orders,10,New customer,6.367797
8,2295261,1,9,1,16,0.0,False,196,4,1,...,7,9.0,both,Mid-range product,Regularly busy,Busiest days,Most orders,10,New customer,6.367797
9,2550362,1,10,4,8,30.0,False,196,1,1,...,7,9.0,both,Mid-range product,Least busy,Slowest days,Most orders,10,New customer,6.367797
10,2968173,15,15,1,9,7.0,False,196,2,0,...,7,9.0,both,Mid-range product,Regularly busy,Busiest days,Most orders,22,Regular customer,3.980556
11,1870022,15,17,2,16,8.0,False,196,6,1,...,7,9.0,both,Mid-range product,Regularly busy,Regularly busy,Most orders,22,Regular customer,3.980556
12,1911383,15,18,2,11,7.0,False,196,1,1,...,7,9.0,both,Mid-range product,Regularly busy,Regularly busy,Most orders,22,Regular customer,3.980556
13,2715276,15,21,1,9,7.0,False,196,1,1,...,7,9.0,both,Mid-range product,Regularly busy,Busiest days,Most orders,22,Regular customer,3.980556
14,487368,15,22,1,10,14.0,False,196,1,1,...,7,9.0,both,Mid-range product,Regularly busy,Busiest days,Most orders,22,Regular customer,3.980556
15,2293453,19,2,5,14,6.0,False,196,3,0,...,7,9.0,both,Mid-range product,Regularly busy,Regularly busy,Most orders,9,New customer,8.372059
16,1973799,19,5,6,12,8.0,False,196,15,1,...,7,9.0,both,Mid-range product,Regularly busy,Regularly busy,Most orders,9,New customer,8.372059
17,532817,19,7,4,17,6.0,False,196,1,1,...,7,9.0,both,Mid-range product,Least busy,Slowest days,Most orders,9,New customer,8.372059
18,1573906,21,10,3,10,6.0,False,196,2,0,...,7,9.0,both,Mid-range product,Regularly busy,Slowest days,Most orders,33,Regular customer,7.012683
19,1593000,31,10,3,8,7.0,False,196,17,0,...,7,9.0,both,Mid-range product,Regularly busy,Slowest days,Most orders,20,Regular customer,8.137793
20,2231262,31,17,3,11,8.0,False,196,14,1,...,7,9.0,both,Mid-range product,Regularly busy,Slowest days,Most orders,20,Regular customer,8.137793
21,2580647,43,6,4,16,4.0,False,196,9,0,...,7,9.0,both,Mid-range product,Least busy,Slowest days,Most orders,11,Regular customer,7.444898
22,2187180,43,9,4,12,3.0,False,196,1,1,...,7,9.0,both,Mid-range product,Least busy,Slowest days,Most orders,11,Regular customer,7.444898
23,2497897,52,1,1,9,NaN,True,196,4,0,...,7,9.0,both,Mid-range product,Regularly busy,Busiest days,Most orders,27,Regular customer,6.356287
24,1318871,52,2,1,10,7.0,False,196,5,1,...,7,9.0,both,Mid-range product,Regularly busy,Busiest days,Most orders,27,Regular customer,6.356287
25,1261384,52,3,1,10,7.0,False,196,3,1,...,7,9.0,both,Mid-range product,Regularly busy,Busiest days,Most orders,27,Regular customer,6.356287
26,580568,52,5,2,10,8.0,False,196,6,1,...,7,9.0,both,Mid-range product,Regularly busy,Regularly busy,Most orders,27,Regular customer,6.356287
27,2428073,52,7,2,7,8.0,False,196,5,1,...,7,9.0,both,Mid-range product,Regularly busy,Regularly busy,Average orders,27,Regular customer,6.356287
28,342306,52,9,1,11,7.0,False,196,5,1,...,7,9.0,both,Mid-range product,Regularly busy,Busiest days,Most orders,27,Regular customer,6.356287
29,1520353,52,10,2,10,8.0,False,196,4,1,...,7,9.0,both,Mid-range product,Regularly busy,Regularly busy,Most orders,27,Regular customer,6.356287
30,2542086,52,11,2,9,7.0,False,196,3,1,...,7,9.0,both,Mid-range product,Regularly busy,Regularly busy,Most orders,27,Regular customer,6.356287
31,944694,52,12,1,16,6.0,False,196,7,1,...,7,9.0,both,Mid-range product,Regularly busy,Busiest days,Most orders,27,Regular customer,6.356287
32,1268191,52,15,2,11,8.0,False,196,3,1,...,7,9.0,both,Mid-range product,Regularly busy,Regularly busy,Most orders,27,Regular customer,6.356287
33,1122089,52,17,2,10,6.0,False,196,4,1,...,7,9.0,both,Mid-range product,Regularly busy,Regularly busy,Most orders,27,Regular customer,6.356287
34,1498922,52,18,2,10,14.0,False,196,6,1,...,7,9.0,both,Mid-range product,Regularly busy,Regularly busy,Most orders,27,Regular customer,6.356287
35,180919,52,19,3,8,8.0,False,196,4,1,...,7,9.0,both,Mid-range product,Regularly busy,Slowest days,Most orders,27,Regular customer,6.356287
36,2695875,52,21,5,10,30.0,False,196,1,1,...,7,9.0,both,Mid-range product,Regularly busy,Regularly busy,Most orders,27,Regular customer,6.356287
37,3205960,67,1,3,11,NaN,True,196,1,0,...,7,9.0,both,Mid-range product,Regularly busy,Slowest days,Most orders,24,Regular customer,7.656790
38,970922,67,2,1,15,5.0,False,196,2,1,...,7,9.0,both,Mid-range product,Regularly busy,Busiest days,Most orders,24,Regular customer,7.656790
39,596585,67,3,1,13,7.0,False,196,2,1,...,7,9.0,both,Mid-range product,Regularly busy,Busiest days,Most orders,24,Regular customer,7.656790
40,2037087,67,4,2,9,8.0,False,196,1,1,...,7,9.0,both,Mid-range product,Regularly busy,Regularly busy,Most orders,24,Regular customer,7.656790
41,2474111,67,5,3,14,8.0,False,196,2,1,...,7,9.0,both,Mid-range product,Regularly busy,Slowest days,Most orders,24,Regular customer,7.656790
42,1568481,67,6,3,12,7.0,False,196,2,1,...,7,9.0,both,Mid-range product,Regularly busy,Slowest days,Most orders,24,Regular customer,7.656790
43,2048527,67,8,2,11,7.0,False,196,1,1,...,7,9.0,both,Mid-range product,Regularly busy,Regularly busy,Most orders,24,Regular customer,7.656790
44,2389031,67,9,2,14,7.0,False,196,1,1,...,7,9.0,both,Mid-range product,Regularly busy,Regularly busy,Most orders,24,Regular customer,7.656790
45,2378562,67,10,1,10,6.0,False,196,1,1,...,7,9.0,both,Mid-range product,Regularly busy,Busiest days,Most orders,24,Regular customer,7.656790
46,1515698,67,11,1,11,7.0,False,196,1,1,...,7,9.0,both,Mid-range product,Regularly busy,Busiest days,Most orders,24,Regular customer,7.656790
47,1928050,67,12,2,12,8.0,False,196,1,1,...,7,9.0,both,Mid-range product,Regularly busy,Regularly busy,Most orders,24,Regular customer,7.656790
48,1949274,67,13,1,10,6.0,False,196,1,1,...,7,9.0,both,Mid-range product,Regularly busy,Busiest days,Most orders,24,Regular customer,7.656790
49,551869,67,14,1,9,7.0,False,196,1,1,...,7,9.0,both,Mid-range product,Regularly busy,Busiest days,Most orders,24,Regular customer,7.656790

In [23]:
# FLAG: Low spender (lowest average price value)

ords_prods_merge.loc[ords_prods_merge['average_price'] < 10, 'spender_flag'] = 'Low spender'

In [24]:
# FLAG: High spender (highest average price value)

ords_prods_merge.loc[ords_prods_merge['average_price'] >= 10, 'spender_flag'] = 'High spender'

In [25]:
# Check Output of spender flag 

ords_prods_merge['spender_flag'].value_counts(dropna = False)

Low spender     31770614
High spender      634245
Name: spender_flag, dtype: int64

In [26]:
# Check columns of spender flag

ords_prods_merge[['customer_id', 'spender_flag', 'average_price']].head(60)

    customer_id spender_flag  average_price
0             1  Low spender       6.367797
1             1  Low spender       6.367797
2             1  Low spender       6.367797
3             1  Low spender       6.367797
4             1  Low spender       6.367797
5             1  Low spender       6.367797
6             1  Low spender       6.367797
7             1  Low spender       6.367797
8             1  Low spender       6.367797
9             1  Low spender       6.367797
10           15  Low spender       3.980556
11           15  Low spender       3.980556
12           15  Low spender       3.980556
13           15  Low spender       3.980556
14           15  Low spender       3.980556
15           19  Low spender       8.372059
16           19  Low spender       8.372059
17           19  Low spender       8.372059
18           21  Low spender       7.012683
19           31  Low spender       8.137793
20           31  Low spender       8.137793
21           43  Low spender       7.444898
22           43  Low spender       7.444898
23           52  Low spender       6.356287
24           52  Low spender       6.356287
25           52  Low spender       6.356287
26           52  Low spender       6.356287
27           52  Low spender       6.356287
28           52  Low spender       6.356287
29           52  Low spender       6.356287
30           52  Low spender       6.356287
31           52  Low spender       6.356287
32           52  Low spender       6.356287
33           52  Low spender       6.356287
34           52  Low spender       6.356287
35           52  Low spender       6.356287
36           52  Low spender       6.356287
37           67  Low spender       7.656790
38           67  Low spender       7.656790
39           67  Low spender       7.656790
40           67  Low spender       7.656790
41           67  Low spender       7.656790
42           67  Low spender       7.656790
43           67  Low spender       7.656790
44           67  Low spender       7.656790
45           67  Low spender       7.656790
46           67  Low spender       7.656790
47           67  Low spender       7.656790
48           67  Low spender       7.656790
49           67  Low spender       7.656790
50           67  Low spender       7.656790
51           67  Low spender       7.656790
52           67  Low spender       7.656790
53           67  Low spender       7.656790
54           67  Low spender       7.656790
55           67  Low spender       7.656790
56           81  Low spender       8.165385
57           81  Low spender       8.165385
58           82  Low spender       6.441221
59           82  Low spender       6.441221

** **
**Q7. In order to send relevant notifications to users within the app (for instance, asking users if they want to buy the same item again), the Instacart team wants you to determine frequent versus non-frequent customers. Create an order frequency flag that marks the regularity of a user’s ordering behavior according to the median in the “days_since_prior_order” column. The criteria for the flag should be as follows:**

- If the median of “days_since_prior_order” is higher than 20, then the customer should be labeled a “Non-frequent customer.”
- If the median is higher than 10 and lower than or equal to 20, then the customer should be labeled a “Regular customer.”
- If the median is lower than or equal to 10, then the customer should be labeled a “Frequent customer.”

In [27]:
# MEDIAN FLAG (for days_since_prior_order): Create median_days_since_prior_order column with aggregated median days_since_prior_order by customer_id

ords_prods_merge['median_days_since_prior_order'] = ords_prods_merge.groupby(['customer_id'])['days_since_prior_order'].transform(np.median)

In [28]:
# Check Output

ords_prods_merge.head(50)

,order_id,customer_id,order_number,order_day_of_week,order_hour_of_day,days_since_prior_order,new_customer,product_id,add_to_cart_order,reordered,...,_merge,price_range,busiest_day,busiest days,busiest_period_of_day,max_order,loyalty_flag,average_price,spender_flag,median_days_since_prior_order
0,2539329,1,1,2,8,NaN,True,196,1,0,...,both,Mid-range product,Regularly busy,Regularly busy,Most orders,10,New customer,6.367797,Low spender,20.5
1,2398795,1,2,3,7,15.0,False,196,1,1,...,both,Mid-range product,Regularly busy,Slowest days,Average orders,10,New customer,6.367797,Low spender,20.5
2,473747,1,3,3,12,21.0,False,196,1,1,...,both,Mid-range product,Regularly busy,Slowest days,Most orders,10,New customer,6.367797,Low spender,20.5
3,2254736,1,4,4,7,29.0,False,196,1,1,...,both,Mid-range product,Least busy,Slowest days,Average orders,10,New customer,6.367797,Low spender,20.5
4,431534,1,5,4,15,28.0,False,196,1,1,...,both,Mid-range product,Least busy,Slowest days,Most orders,10,New customer,6.367797,Low spender,20.5
5,3367565,1,6,2,7,19.0,False,196,1,1,...,both,Mid-range product,Regularly busy,Regularly busy,Average orders,10,New customer,6.367797,Low spender,20.5
6,550135,1,7,1,9,20.0,False,196,1,1,...,both,Mid-range product,Regularly busy,Busiest days,Most orders,10,New customer,6.367797,Low spender,20.5
7,3108588,1,8,1,14,14.0,False,196,2,1,...,both,Mid-range product,Regularly busy,Busiest days,Most orders,10,New customer,6.367797,Low spender,20.5
8,2295261,1,9,1,16,0.0,False,196,4,1,...,both,Mid-range product,Regularly busy,Busiest days,Most orders,10,New customer,6.367797,Low spender,20.5
9,2550362,1,10,4,8,30.0,False,196,1,1,...,both,Mid-range product,Least busy,Slowest days,Most orders,10,New customer,6.367797,Low spender,20.5
10,2968173,15,15,1,9,7.0,False,196,2,0,...,both,Mid-range product,Regularly busy,Busiest days,Most orders,22,Regular customer,3.980556,Low spender,10.0
11,1870022,15,17,2,16,8.0,False,196,6,1,...,both,Mid-range product,Regularly busy,Regularly busy,Most orders,22,Regular customer,3.980556,Low spender,10.0
12,1911383,15,18,2,11,7.0,False,196,1,1,...,both,Mid-range product,Regularly busy,Regularly busy,Most orders,22,Regular customer,3.980556,Low spender,10.0
13,2715276,15,21,1,9,7.0,False,196,1,1,...,both,Mid-range product,Regularly busy,Busiest days,Most orders,22,Regular customer,3.980556,Low spender,10.0
14,487368,15,22,1,10,14.0,False,196,1,1,...,both,Mid-range product,Regularly busy,Busiest days,Most orders,22,Regular customer,3.980556,Low spender,10.0
15,2293453,19,2,5,14,6.0,False,196,3,0,...,both,Mid-range product,Regularly busy,Regularly busy,Most orders,9,New customer,8.372059,Low spender,6.0
16,1973799,19,5,6,12,8.0,False,196,15,1,...,both,Mid-range product,Regularly busy,Regularly busy,Most orders,9,New customer,8.372059,Low spender,6.0
17,532817,19,7,4,17,6.0,False,196,1,1,...,both,Mid-range product,Least busy,Slowest days,Most orders,9,New customer,8.372059,Low spender,6.0
18,1573906,21,10,3,10,6.0,False,196,2,0,...,both,Mid-range product,Regularly busy,Slowest days,Most orders,33,Regular customer,7.012683,Low spender,7.5
19,1593000,31,10,3,8,7.0,False,196,17,0,...,both,Mid-range product,Regularly busy,Slowest days,Most orders,20,Regular customer,8.137793,Low spender,6.0
20,2231262,31,17,3,11,8.0,False,196,14,1,...,both,Mid-range product,Regularly busy,Slowest days,Most orders,20,Regular customer,8.137793,Low spender,6.0
21,2580647,43,6,4,16,4.0,False,196,9,0,...,both,Mid-range product,Least busy,Slowest days,Most orders,11,Regular customer,7.444898,Low spender,10.0
22,2187180,43,9,4,12,3.0,False,196,1,1,...,both,Mid-range product,Least busy,Slowest days,Most orders,11,Regular customer,7.444898,Low spender,10.0
23,2497897,52,1,1,9,NaN,True,196,4,0,...,both,Mid-range product,Regularly busy,Busiest days,Most orders,27,Regular customer,6.356287,Low spender,8.0
24,1318871,52,2,1,10,7.0,False,196,5,1,...,both,Mid-range product,Regularly busy,Busiest days,Most orders,27,Regular customer,6.356287,Low spender,8.0
25,1261384,52,3,1,10,7.0,False,196,3,1,...,both,Mid-range product,Regularly busy,Busiest days,Most orders,27,Regular customer,6.356287,Low spender,8.0
26,580568,52,5,2,10,8.0,False,196,6,1,...,both,Mid-range product,Regularly busy,Regularly busy,Most orders,27,Regular customer,6.356287,Low spender,8.0
27,2428073,52,7,2,7,8.0,False,196,5,1,...,both,Mid-range product,Regularly busy,Regularly busy,Average orders,27,Regular customer,6.356287,Low spender,8.0
28,342306,52,9,1,11,7.0,False,196,5,1,...,both,Mid-range product,Regularly busy,Busiest days,Most orders,27,Regular customer,6.356287,Low spender,8.0
29,1520353,52,10,2,10,8.0,False,196,4,1,...,both,Mid-range product,Regularly busy,Regularly busy,Most orders,27,Regular customer,6.356287,Low spender,8.0
30,2542086,52,11,2,9,7.0,False,196,3,1,...,both,Mid-range product,Regularly busy,Regularly busy,Most orders,27,Regular customer,6.356287,Low spender,8.0
31,944694,52,12,1,16,6.0,False,196,7,1,...,both,Mid-range product,Regularly busy,Busiest days,Most orders,27,Regular customer,6.356287,Low spender,8.0
32,1268191,52,15,2,11,8.0,False,196,3,1,...,both,Mid-range product,Regularly busy,Regularly busy,Most orders,27,Regular customer,6.356287,Low spender,8.0
33,1122089,52,17,2,10,6.0,False,196,4,1,...,both,Mid-range product,Regularly busy,Regularly busy,Most orders,27,Regular customer,6.356287,Low spender,8.0
34,1498922,52,18,2,10,14.0,False,196,6,1,...,both,Mid-range product,Regularly busy,Regularly busy,Most orders,27,Regular customer,6.356287,Low spender,8.0
35,180919,52,19,3,8,8.0,False,196,4,1,...,both,Mid-range product,Regularly busy,Slowest days,Most orders,27,Regular customer,6.356287,Low spender,8.0
36,2695875,52,21,5,10,30.0,False,196,1,1,...,both,Mid-range product,Regularly busy,Regularly busy,Most orders,27,Regular customer,6.356287,Low spender,8.0
37,3205960,67,1,3,11,NaN,True,196,1,0,...,both,Mid-range product,Regularly busy,Slowest days,Most orders,24,Regular customer,7.656790,Low spender,7.0
38,970922,67,2,1,15,5.0,False,196,2,1,...,both,Mid-range product,Regularly busy,Busiest days,Most orders,24,Regular customer,7.656790,Low spender,7.0
39,596585,67,3,1,13,7.0,False,196,2,1,...,both,Mid-range product,Regularly busy,Busiest days,Most orders,24,Regular customer,7.656790,Low spender,7.0
40,2037087,67,4,2,9,8.0,False,196,1,1,...,both,Mid-range product,Regularly busy,Regularly busy,Most orders,24,Regular customer,7.656790,Low spender,7.0
41,2474111,67,5,3,14,8.0,False,196,2,1,...,both,Mid-range product,Regularly busy,Slowest days,Most orders,24,Regular customer,7.656790,Low spender,7.0
42,1568481,67,6,3,12,7.0,False,196,2,1,...,both,Mid-range product,Regularly busy,Slowest days,Most orders,24,Regular customer,7.656790,Low spender,7.0
43,2048527,67,8,2,11,7.0,False,196,1,1,...,both,Mid-range product,Regularly busy,Regularly busy,Most orders,24,Regular customer,7.656790,Low spender,7.0
44,2389031,67,9,2,14,7.0,False,196,1,1,...,both,Mid-range product,Regularly busy,Regularly busy,Most orders,24,Regular customer,7.656790,Low spender,7.0
45,2378562,67,10,1,10,6.0,False,196,1,1,...,both,Mid-range product,Regularly busy,Busiest days,Most orders,24,Regular customer,7.656790,Low spender,7.0
46,1515698,67,11,1,11,7.0,False,196,1,1,...,both,Mid-range product,Regularly busy,Busiest days,Most orders,24,Regular customer,7.656790,Low spender,7.0
47,1928050,67,12,2,12,8.0,False,196,1,1,...,both,Mid-range product,Regularly busy,Regularly busy,Most orders,24,Regular customer,7.656790,Low spender,7.0
48,1949274,67,13,1,10,6.0,False,196,1,1,...,both,Mid-range product,Regularly busy,Busiest days,Most orders,24,Regular customer,7.656790,Low spender,7.0
49,551869,67,14,1,9,7.0,False,196,1,1,...,both,Mid-range product,Regularly busy,Busiest days,Most orders,24,Regular customer,7.656790,Low spender,7.0

In [29]:
## MEDIAN FLAG: Non-frequent customer (lowest median days_since_prior_order value)

ords_prods_merge.loc[ords_prods_merge['median_days_since_prior_order'] > 20, 'order_frequency_flag'] = 'Non-frequent customer'

In [30]:
# MEDIAN FLAG: Regular customer (middle median days_since_prior_order value)

ords_prods_merge.loc[(ords_prods_merge['median_days_since_prior_order'] > 10) & (ords_prods_merge['median_days_since_prior_order'] <= 20), 'order_frequency_flag'] = 'Regular customer'

In [31]:
# MEDIAN FLAG: Frequent customer (highest median days_since_prior_order value)

ords_prods_merge.loc[ords_prods_merge['median_days_since_prior_order'] <= 10, 'order_frequency_flag'] = 'Frequent customer'

In [32]:
# Check Output of MEDIAN FLAG

ords_prods_merge['order_frequency_flag'].value_counts(dropna = False)

Frequent customer        21559853
Regular customer          7208564
Non-frequent customer     3636437
NaN                             5
Name: order_frequency_flag, dtype: int64

**OBSERVATION:** There's 5 (NaN) missing values found, assuming these entries were recently added orders into the system. The records will be removed from the updated DataFrame file to maintain data consistency.

In [33]:
# Missing Value Subset

ords_prods_merge_nan = ords_prods_merge.loc[ords_prods_merge['order_frequency_flag'].isnull()==True]

ords_prods_merge_nan.shape

(5, 25)

In [34]:
# Check DataFrame Dimension (before removing missing values in order frequency flag column)

ords_prods_merge.shape

(32404859, 25)

In [35]:
# Create new products dataframe without missing values and Check DataFrame dimension

ords_prods_merge_clean = ords_prods_merge[ords_prods_merge['order_frequency_flag'].isnull()==False]

ords_prods_merge_clean.shape

(32404854, 25)

In [36]:
# Check Output of MEDIAN FLAG

ords_prods_merge_clean[['customer_id', 'spender_flag', 'order_frequency_flag', 'median_days_since_prior_order']].head(60)

,customer_id,spender_flag,order_frequency_flag,median_days_since_prior_order
0,1,Low spender,Non-frequent customer,20.5
1,1,Low spender,Non-frequent customer,20.5
2,1,Low spender,Non-frequent customer,20.5
3,1,Low spender,Non-frequent customer,20.5
4,1,Low spender,Non-frequent customer,20.5
5,1,Low spender,Non-frequent customer,20.5
6,1,Low spender,Non-frequent customer,20.5
7,1,Low spender,Non-frequent customer,20.5
8,1,Low spender,Non-frequent customer,20.5
9,1,Low spender,Non-frequent customer,20.5
10,15,Low spender,Frequent customer,10.0
11,15,Low spender,Frequent customer,10.0
12,15,Low spender,Frequent customer,10.0
13,15,Low spender,Frequent customer,10.0
14,15,Low spender,Frequent customer,10.0
15,19,Low spender,Frequent customer,6.0
16,19,Low spender,Frequent customer,6.0
17,19,Low spender,Frequent customer,6.0
18,21,Low spender,Frequent customer,7.5
19,31,Low spender,Frequent customer,6.0
20,31,Low spender,Frequent customer,6.0
21,43,Low spender,Frequent customer,10.0
22,43,Low spender,Frequent customer,10.0
23,52,Low spender,Frequent customer,8.0
24,52,Low spender,Frequent customer,8.0
25,52,Low spender,Frequent customer,8.0
26,52,Low spender,Frequent customer,8.0
27,52,Low spender,Frequent customer,8.0
28,52,Low spender,Frequent customer,8.0
29,52,Low spender,Frequent customer,8.0
30,52,Low spender,Frequent customer,8.0
31,52,Low spender,Frequent customer,8.0
32,52,Low spender,Frequent customer,8.0
33,52,Low spender,Frequent customer,8.0
34,52,Low spender,Frequent customer,8.0
35,52,Low spender,Frequent customer,8.0
36,52,Low spender,Frequent customer,8.0
37,67,Low spender,Frequent customer,7.0
38,67,Low spender,Frequent customer,7.0
39,67,Low spender,Frequent customer,7.0
40,67,Low spender,Frequent customer,7.0
41,67,Low spender,Frequent customer,7.0
42,67,Low spender,Frequent customer,7.0
43,67,Low spender,Frequent customer,7.0
44,67,Low spender,Frequent customer,7.0
45,67,Low spender,Frequent customer,7.0
46,67,Low spender,Frequent customer,7.0
47,67,Low spender,Frequent customer,7.0
48,67,Low spender,Frequent customer,7.0
49,67,Low spender,Frequent customer,7.0
50,67,Low spender,Frequent customer,7.0
51,67,Low spender,Frequent customer,7.0
52,67,Low spender,Frequent customer,7.0
53,67,Low spender,Frequent customer,7.0
54,67,Low spender,Frequent customer,7.0
55,67,Low spender,Frequent customer,7.0
56,81,Low spender,Non-frequent customer,30.0
57,81,Low spender,Non-frequent customer,30.0
58,82,Low spender,Regular customer,11.5
59,82,Low spender,Regular customer,11.5

**OBSERVATION:** Low spenders seems to have more frequesnt buying habits with multiple purchased items.

#### 7. EXPORTING UPDATED DATAFRAME

In [37]:
# Export to PICKLE

ords_prods_merge_clean.to_pickle(os.path.join(path, '02 Data','Prepared Data', 'orders_products_merged_update2.pkl'))